version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: orthoandspinetools-postgres
    environment:
      POSTGRES_DB: orthoandspinetools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orthoandspinetools-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: orthoandspinetools-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:password@postgres:5432/orthoandspinetools
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: https://orthoandspinetools.com
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - orthoandspinetools-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: orthoandspinetools-frontend
    environment:
      VITE_API_URL: https://orthoandspinetools.com/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - orthoandspinetools-network

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: orthoandspinetools-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/letsencrypt:/etc/letsencrypt
      - ./nginx/ssl/certbot:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - orthoandspinetools-network

  # Certbot for Let's Encrypt
  certbot:
    image: certbot/certbot
    container_name: orthoandspinetools-certbot
    volumes:
      - ./nginx/ssl/letsencrypt:/etc/letsencrypt
      - ./nginx/ssl/certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@orthoandspinetools.com --agree-tos --no-eff-email -d orthoandspinetools.com -d www.orthoandspinetools.com

volumes:
  postgres_data:

networks:
  orthoandspinetools-network:
    driver: bridge
